apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}-app
  # title: Wayfinder Application
  description: Application created from the backstage software template
  labels: {}
  annotations:
    backstage.io/source-location: url:https://${{values.repo.host + "/" + values.repo.owner + "/" + values.repo.repo}}
    github.com/project-slug: ${{values.repo.owner + "/" + values.repo.repo}}
    sonarqube.org/project-key: ${{values.repo.owner + "_" + values.repo.repo}}
    backstage.io/techdocs-ref: url:https://${{values.repo.host + "/" + values.repo.owner + "/" + values.repo.repo}}/tree/main
    jfrog-artifactory/image-name: ${{ values.artifactoryDockerRepo }}/${{ values.name }}
    wayfinder/workspace: ${{ values.workspaceKey }}    
    wayfinder/app-name: ${{ values.name }}
    wayfinder/app-component-name: ${{ values.name }}-app
    # Grafana dashboard annotation - will show dashboards with the app's tag
    grafana/dashboard-selector: "tags @> '${{ values.name }}'"
  tags:
    - wayfinder
  links:
    - url: https://${{values.repo.host + "/" + values.repo.owner + "/" + values.repo.repo}}
      title: GitHub Repository
      type: Code
      icon: github
    - url: https://${{values.repo.host + "/" + values.repo.owner + "/" + values.repo.repo}}/actions
      title: GitHub Actions
      type: CI/CD
      icon: github
    - url: https://${{values.repo.host + "/" + values.repo.owner + "/" + values.repo.repo}}/releases
      title: Releases
      type: Release
      icon: github
    - url: https://sonarcloud.io/project/overview?id=${{values.repo.owner + "_" + values.repo.repo}}
      title: SonarCloud Quality Gate
      type: Quality
      icon: sonarcloud
    - url: https://portal.backstage.prod.wf.appvia.io/catalog/default/component/${{ values.name }}-app
      title: Production Backstage
      type: Backstage
      icon: backstage
    - url: https://${{ values.artifactoryUrl }}/ui/repos/tree/General/${{ values.artifactoryDockerRepo }}/${{ values.name }}
      title: JFrog Artifactory
      type: Docker Registry
      icon: artifactory
    {%- if values.grafanaDashboardUrl %}
    - url: ${{ values.grafanaDashboardUrl }}
      title: Grafana Dashboard
      type: Monitoring
      icon: dashboard
    {%- endif %}
spec:
  type: service
  owner: ${{ values.owner }}
  lifecycle: experimental
  dependsOn:
    - resource:default/${{ values.name }}-mysql
  providesApis:
    - ${{ values.name }}-api
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.name }}-mysql
  # title: Wayfinder Application DB
  description: AWS RDS MySQL Database used by the Wayfinder Application
  labels: {}
  annotations:
    backstage.io/source-location: url:https://${{values.repo.host + "/" + values.repo.owner + "/" + values.repo.repo}}
    github.com/project-slug: ${{values.repo.owner + "/" + values.repo.repo}}
    sonarqube.org/project-key: ${{values.repo.owner + "_" + values.repo.repo}}
    backstage.io/techdocs-ref: url:https://${{values.repo.host + "/" + values.repo.owner + "/" + values.repo.repo}}/tree/main
    wayfinder/workspace: ${{ values.workspaceKey }}
    wayfinder/app-name: ${{ values.name }}
    wayfinder/app-component-name: ${{ values.name }}-mysql
  tags:
    - wayfinder
  links:
    - url: https://${{values.repo.host + "/" + values.repo.owner + "/" + values.repo.repo}}
      title: GitHub Repository
      type: Code
      icon: github
spec:
  type: database
  owner: ${{ values.owner }}
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.name }}-api
  description: REST API for the ${{ values.name }} todo application with RDS database
  labels: {}
  annotations:
    backstage.io/source-location: url:https://${{values.repo.host + "/" + values.repo.owner + "/" + values.repo.repo}}
    github.com/project-slug: ${{values.repo.owner + "/" + values.repo.repo}}
    backstage.io/techdocs-ref: url:https://${{values.repo.host + "/" + values.repo.owner + "/" + values.repo.repo}}/tree/main
    wayfinder/workspace: ${{ values.workspaceKey }}
    wayfinder/app-name: ${{ values.name }}
  tags:
    - wayfinder
    - rest
    - todo
    - rds
  links:
    - url: https://${{values.repo.host + "/" + values.repo.owner + "/" + values.repo.repo}}
      title: GitHub Repository
      type: Code
      icon: github
    - url: https://${{values.repo.host + "/" + values.repo.owner + "/" + values.repo.repo}}/blob/main/app/openapi.yaml
      title: OpenAPI Specification
      type: API Spec
      icon: openapi
spec:
  type: openapi
  lifecycle: experimental
  owner: ${{ values.owner }}
  definition:
    $text: ./app/openapi.yaml