site_name: ${{values.name | dump}}
site_description: ${{values.description | dump}}

nav:
  - Introduction: index.md
  - Development: development.md
  - RDS Integration: rds-integration.md

plugins:
  - techdocs-core