---
apiVersion: app.appvia.io/v2beta1
kind: AppComponent
metadata:
  name: mysql-${{ values.name }}
spec:
  application: ${{ values.name }}
  cloudResource:
    plan: appvia-rds-mysql
    planVersion: 1.0.0
    variables:
      # db_name below will be prefixed with the app environment name 
      # when component gets deployed as database names must be unique 
      # within the same AWS account. See the referencced CR plan for more info.
      db_name: todos
      allocated_storage: ${{ values.database_allocated_storage }}
      instance_class: ${{ values.database_instance_class }}
  key: mysql
  name: mysql-${{ values.name }}
  type: CloudResource
---
apiVersion: app.appvia.io/v2beta1
kind: AppComponent
metadata:
  name: app-${{ values.name }}
spec:
  application: ${{ values.name }}
  container:
    containers:
      - env:
          - name: MYSQL_HOST
            fromCloudResourceOutput:
              componentName: mysql
              output: DATABASE_HOST
          - name: MYSQL_USER
            fromCloudResourceOutput:
              componentName: mysql
              output: DATABASE_USER
          - name: MYSQL_PASSWORD
            fromCloudResourceOutput:
              componentName: mysql
              output: DATABASE_PASSWORD
          - name: MYSQL_DB
            fromCloudResourceOutput:
              componentName: mysql
              output: DATABASE_NAME
        image: quay.io/appvia/todo-app:latest
        name: app
        ports:
          - containerPort: 3000
            expose: true
            name: http
            protocol: TCP
    expose:
      container: app
      port: 3000
    replicas: 1
    tls: true
  key: app
  name: app-${{ values.name }}
  type: Container
